version: '3.0'

services:

  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 50M

  rinha-api-1:
    image: jhonatanrs/rinha-backend-2024-q1:latest
    container_name: rinha-api-1
    restart: always
    environment:
      - API_PORT=9999
      - SERVER_TYPE=api
      - DB_HOST=rinha-db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=qwerty
      - DB_NAME=rinha-db
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 75M

  rinha-api-2:
    image: jhonatanrs/rinha-backend-2024-q1:latest
    container_name: rinha-api-2
    restart: always
    environment:
      - API_PORT=9999
      - SERVER_TYPE=api
      - DB_HOST=rinha-db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=qwerty
      - DB_NAME=rinha-db
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 75M

  rinha-db:
    image: mysql:8.0
    container_name: rinha-db
    restart: always
    environment:
      - MYSQL_DATABASE=rinha-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - 3306:3306
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./mysql.cnf:/etc/mysql/my.cnf
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 350M        